# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161007_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.URLField(blank=True, default='http://john95013600.pythonanywhere.com/'),
        ),
    ]
